function p = base_parameters()
% Declared simulation parameters, not measured vehicle-identification data.
p.dt = 0.02;
p.T = 120;
p.masses = [20000 24000 28000 22000]; % kg
p.headway = 3.0;                       % s, fixed across cells
p.standstill_gap = 8;                   % m
p.vehicle_length = 12;                 % m
p.ambient_C = 25;
p.initial_temp_C = 105;
p.thermal_capacity = 1.5e5;            % J/K, equivalent brake state
p.thermal_conductance = 650;           % W/K
p.brake_heat_fraction = 0.75;
p.pressure_max = 1.0e6;                 % Pa
p.brake_force_max = 1.2e5;             % N at cool temperature
p.pressure_time_charge = 0.25;         % s
p.pressure_time_exhaust = 0.18;        % s
p.drag_coefficient = 0.60;             % N/(m/s)^2
p.rolling_coefficient = 0.005;
p.grade = -0.04;                        % downhill road slope
p.force_min = -1.2e5;                  % N
p.force_max = 7.0e4;                   % N
p.force_slew = 5.0e5;                  % N/s
p.accel_virtual_limit = 1.5;          % m/s^2
p.accel_virtual_slew = 1.5;            % m/s^3
p.comm_delay = 0.08;                   % s
p.comm_delay_rate = 0.05;
p.dwell = 0.5;                         % s
p.temp_est_error_C = 1.0;              % declared estimate half-width
p.rho_est_error = 0.005;
p.tau_est_error_s = 0.01;
p.warm_delay_threshold_C = 114;       % deterministic pneumatic delay mode
p.stop_gap = 3.0;                      % m
p.stop_trigger = 1.0;                  % m
p.stop_response = 0.4;                 % s
p.stop_preaccel = 0.4;                 % m/s^2
p.fallback_ke = 0.9440508038221074;
p.fallback_kr = 0.04491616569214696;
p.seed = 17;
end
