function U = build_uncertainty_set(estimate,p)
% Rectangular confidence enclosure for the coordinates used by the cell.
U=struct('mass_kg',[estimate.mass_kg estimate.mass_kg], ...
    'headway_s',[estimate.headway_s estimate.headway_s], ...
    'temp_C',[estimate.temp_C-p.temp_est_error_C estimate.temp_C+p.temp_est_error_C], ...
    'pressure_Pa',[estimate.pressure_Pa estimate.pressure_Pa], ...
    'rho_factor',[estimate.rho_factor-p.rho_est_error estimate.rho_factor+p.rho_est_error], ...
    'tau_a_s',[estimate.tau_a_s-p.tau_est_error_s estimate.tau_a_s+p.tau_est_error_s]);
end
