function inside = cell_contains_uncertainty(U,c)
inside = contained(U.mass_kg,c.mass_kg) ...
    && contained(U.headway_s,[c.h c.h]) ...
    && contained(U.temp_C,c.temp_C) ...
    && contained(U.pressure_Pa,c.pressure_Pa) ...
    && contained(U.rho_factor,c.rho_factor) ...
    && contained(U.tau_a_s,c.tau_a_range);
end
function tf=contained(small,large)
tf=all(isfinite(small)) && small(1)>=large(1) && small(2)<=large(2);
end
